name: flutter_ume_kit_ui
description: UI Kits for flutter_ume.
version: 0.2.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2
  flutter_ume:
    path: ../../../flutter_ume

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: master

flutter:
